import { createSlice } from "@reduxjs/toolkit";



const initialState = {
   name : 'Trinity',
    listViewurl :'http://bgems.benmoredata.com/api/wslistview_mysql.php',
    loginUrl:'http://bgems.benmoredata.com/api/LController.php',
    authUrl:'http://bgems.benmoredata.com/api/auth.php',
    comboUrl:'http://bgems.benmoredata.com/api/APIController.php',
    apiUrl :'http://bgems.benmoredata.com/api/APIController.php',
    imgUploadUrl:'http://bgems.benmoredata.com/imgup.php',
    imageUrl:'http://bgems.benmoredata.com/uploads/images/',
    imageNameUpdateUrl:'http://bgems.benmoredata.com/api/CMController.php',
    attachmentUrl:'http://bgems.benmoredata.com/uploads/attachments/',
    fileUploadUrl:'http://bgems.benmoredata.com/fileupload.php',
    pcdurl:'http://bgems.benmoredata.com/api/PCDController.php',
    pdfurl:'http://bgems.benmoredata.com/tcpdf/',
    indentUrl:'http://bgems.benmoredata.com/api/IndentController.php',
    invoiceUrl:'http://bgems.benmoredata.com/api/InvoiceController.php',
    commonUrl : 'http://bgems.benmoredata.com/api/CommonController.php',
    bomCopyUrl: 'http://bgems.benmoredata.com/api/VersioningController.php',
    bomHeaderUrl: 'http://bgems.benmoredata.com/api/BOMController.php',
    stockUrl:'http://bgems.benmoredata.com/api/StockController.php',
    batchUrl:'http://bgems.benmoredata.com/api/BatchstructureController.php',
    finalinvUrl:'http://bgems.benmoredata.com/api/FinalInvoiceController.php',
    proformainvUrl:'http://bgems.benmoredata.com/api/ProfoinvoiceController.php',
    orderUrl:'http://bgems.benmoredata.com/api/CustomerOrder.php',
    stockReqUrl:'http://bgems.benmoredata.com/api/StockRequirement.php',
    productUrl:'http://bgems.benmoredata.com/api/StockProcedure.php',
    bomLkUrl:'http://bgems.benmoredata.com/api/BOMLeatherCountController.php',
    designPUrl:'http://bgems.benmoredata.com/api/UomconversiongetController.php',
    costingMatrialUrl:'http://bgems.benmoredata.com/api/BomcostController.php?',
    conversionUrl:'http://bgems.benmoredata.com/api/UomconversiongetController.php',
    userGroupUrl:'http://bgems.benmoredata.com/api/GroupaccessController.php',
    dcTrackingUrl:'http://bgems.benmoredata.com/api/DctrackingController.php',
    trackingUrl:'http://bgems.benmoredata.com/api/MaterialtrackingController.php',
    supplierTrackUrl:'http://bgems.benmoredata.com/api/SuppliertrackingController.php',
    materialsTrackingUrl:'http://bgems.benmoredata.com/api/MaterialTrackingChart.php',
    supplytrackingUrl:'http://bgems.benmoredata.com/api/SupplierTrackingChart.php',
    producttrackingUrl:'http://bgems.benmoredata.com/api/ProductpriceController.php?',
    customerorderanalysisUrl:'http://bgems.benmoredata.com/api/CustomerOrderChart.php?',
    prductorderanalysisUrl:'http://bgems.benmoredata.com/api/ProductOrderChart.php?',
    mailContentGeturl:'http://bgems.benmoredata.com/api/EmailController.php',
    mailSendUrl:'http://bgems.benmoredata.com/api/invoicemail.php',
    materialUomCovUrl:'http://bgems.benmoredata.com/api/MaterialUOMConversionController.php',
    decryptUrl:'http://bgems.benmoredata.com/api/HashtokenController.php',
    costingLeatherUrl:'http://bgems.benmoredata.com/api/BomLeathercost.php',
    customerLeatherUrl:'http://bgems.benmoredata.com/api/CustomerLeatherController.php',
    getempdeploymentUrl:'http://bgems.benmoredata.com/api/getempdeployment.php?',
    postempdeployment:'http://bgems.benmoredata.com/api/postempdeployment.php?',
    matProcurementUrl:'http://bgems.benmoredata.com/api/MaterialProcurementChart.php',
    stockorderUrl:'http://bgems.benmoredata.com/api/MaterialOrderReportController.php',
    dcsummaryUrl:'http://bgems.benmoredata.com/api/getdcsummary.php',
    dcpostsummaryUrl:'http://bgems.benmoredata.com/api/postdcsummary.php',
    packinglistCbmUrl:'http://bgems.benmoredata.com/api/CbmCalculation.php',
    searchUrl:'http://bgems.benmoredata.com/api/productSearch3.php',
    bomCopyJobworkUrl:'http://bgems.benmoredata.com/api/JobworkversionController.php',
    jobworkbomurl:'http://bgems.benmoredata.com/api/JobworkController.php',
    alterNateMaterial:'http://bgems.benmoredata.com/api/AlterMaterialControllertemp.php',
    PurchaseOrderParameterUrl:'http://bgems.benmoredata.com/api/APIController.php',
    PurchaseorderratingUrl:'http://bgems.benmoredata.com/api/ParametergetController.php',
    CustomerPriceorderQtyUrl:'http://bgems.benmoredata.com/api/InternalorderController.php',
 
  
    // listViewurl :'https://lgems.beyondexs.com/api/wslistview_mysql.php',
    // loginUrl:'https://lgems.beyondexs.com/api/LController.php',
    // authUrl:'https://lgems.beyondexs.com/api/auth.php',
    // comboUrl:'https://lgems.beyondexs.com/api/APIController.php',
    // apiUrl :'https://lgems.beyondexs.com/api/APIController.php',
    // imgUploadUrl:'https://lgems.beyondexs.com/imgup.php',
    // imageUrl:'https://lgems.beyondexs.com/uploads/images/',
    // imageNameUpdateUrl:'https://lgems.beyondexs.com/api/CMController.php',
    // attachmentUrl:'https://lgems.beyondexs.com/uploads/attachments/',
    // fileUploadUrl:'https://lgems.beyondexs.com/fileupload.php',
    // pcdurl:'https://lgems.beyondexs.com/api/PCDController.php',
    // pdfurl:'https://lgems.beyondexs.com/tcpdf/',
    // indentUrl:'https://lgems.beyondexs.com/api/IndentController.php',
    // invoiceUrl:'https://lgems.beyondexs.com/api/InvoiceController.php',
    // commonUrl : 'https://lgems.beyondexs.com/api/CommonController.php',
    // bomCopyUrl: 'https://lgems.beyondexs.com/api/VersioningController.php',
    // bomHeaderUrl: 'https://lgems.beyondexs.com/api/BOMController.php',
    // stockUrl:'https://lgems.beyondexs.com/api/StockController.php',
    // batchUrl:'https://lgems.beyondexs.com/api/BatchstructureController.php',
    // finalinvUrl:'https://lgems.beyondexs.com/api/FinalInvoiceController.php',
    // proformainvUrl:'https://lgems.beyondexs.com/api/ProfoinvoiceController.php',
    // orderUrl:'https://lgems.beyondexs.com/api/CustomerOrder.php',
    // stockReqUrl:'https://lgems.beyondexs.com/api/StockRequirement.php',
    // productUrl:'https://lgems.beyondexs.com/api/StockProcedure.php',
    // bomLkUrl:'https://lgems.beyondexs.com/api/BOMLeatherCountController.php',
    // designPUrl:'https://lgems.beyondexs.com/api/UomconversiongetController.php',
    // costingMatrialUrl:'https://lgems.beyondexs.com/api/BomcostController.php?',
    // conversionUrl:'https://lgems.beyondexs.com/api/UomconversiongetController.php',
    // userGroupUrl:'https://lgems.beyondexs.com/api/GroupaccessController.php',
    // dcTrackingUrl:'https://lgems.beyondexs.com/api/DctrackingController.php',
    // trackingUrl:'https://lgems.beyondexs.com/api/MaterialtrackingController.php',
    // supplierTrackUrl:'https://lgems.beyondexs.com/api/SuppliertrackingController.php',
    // materialsTrackingUrl:'https://lgems.beyondexs.com/api/MaterialTrackingChart.php',
    // supplytrackingUrl:'https://lgems.beyondexs.com/api/SupplierTrackingChart.php',
    // producttrackingUrl:'https://lgems.beyondexs.com/api/ProductpriceController.php?',
    // customerorderanalysisUrl:'https://lgems.beyondexs.com/api/CustomerOrderChart.php?',
    // prductorderanalysisUrl:'https://lgems.beyondexs.com/api/ProductOrderChart.php?',
    // mailContentGeturl:'https://lgems.beyondexs.com/api/EmailController.php',
    // mailSendUrl:'https://lgems.beyondexs.com/api/invoicemail.php',
    // materialUomCovUrl:'https://lgems.beyondexs.com/api/MaterialUOMConversionController.php',
    // decryptUrl:'https://lgems.beyondexs.com/api/HashtokenController.php',
    // costingLeatherUrl:'https://lgems.beyondexs.com/api/BomLeathercost.php',
    // customerLeatherUrl:'https://lgems.beyondexs.com/api/CustomerLeatherController.php',
    // getempdeploymentUrl:'https://lgems.beyondexs.com/api/getempdeployment.php?',
    // postempdeployment:'https://lgems.beyondexs.com/api/postempdeployment.php?',
    // matProcurementUrl:'https://lgems.beyondexs.com/api/MaterialProcurementChart.php',
    // stockorderUrl:'https://lgems.beyondexs.com/api/MaterialOrderReportController.php',
    // dcsummaryUrl:'https://lgems.beyondexs.com/api/getdcsummary.php',
    // dcpostsummaryUrl:'https://lgems.beyondexs.com/api/postdcsummary.php',
    // packinglistCbmUrl:'https://lgems.beyondexs.com/api/CbmCalculation.php',
    // searchUrl:'https://lgems.beyondexs.com/api/productSearch3.php',
    // // searchUrl:'https://localhost:8080/MYPROJECT/bgems-api/productSearch.php',
    // jobworkbomurl:'https://lgems.beyondexs.com/api/JobworkController.php',
    // alterNateMaterial:'https://lgems.beyondexs.com/api/AlterMaterialController.php',
    // PurchaseOrderParameterUrl:'https://lgems.beyondexs.com/api/APIController.php',
    // PurchaseorderratingUrl:'https://lgems.beyondexs.com/api/ParametergetController.php',
    // CustomerPriceorderQtyUrl:'https://lgems.beyondexs.com/api/InternalorderController.php',
    // employeeattendanceUrl:"https://lgems.beyondexs.com/api/getempattendancehistory.php",
    // attendanceUrl:"https://lgems.beyondexs.com/api/getempattendance.php"

  };

export const getUrlSlice = createSlice({
  name: "globalurl",
  initialState,
  reducers: {},
});

export default getUrlSlice.reducer;
